name = "To the Skies"
author = "MsKarMagick, Big Barza"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5846225f3beec45cb7ea42160ca9d6d249474c57f1f9994ea94548830f1dc3e0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
