name = "To the Skies"
author = "MsKarMagick, Big Barza"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de77df759777523fba49ef86c322c6265ea54e7de0ce8ba56c60983ceae6f052"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
