name = "To the Skies"
author = "MsKarMagick, Big Barza"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "831e0911b5750db6fb02f97e5c9eacdbc76bb32dd57a3fb75752a3841414ec45"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
