// Visit the wiki for more info - https://kubejs.com/
console.info('Disabling a lotta stuff')

ServerEvents.recipes(event => {
    event.remove({id: 'createaddition:compacting/seed_oil'})
    event.remove({ output: 'createaddition:capacitor' })
    event.remove({ output: 'createaddition:electrum_amulet' })
    event.remove({ output: 'createaddition:electrum_ingot' })
    event.remove({ output: 'createaddition:electrum_nugget' })
    event.remove({ output: 'createaddition:electrum_sheet' })
    event.remove({ output: 'createaddition:zinc_sheet' })
    event.remove({ output: 'createaddition:copper_wire' })
    event.remove({ output: 'createaddition:iron_wire' })
    event.remove({ output: 'createaddition:gold_wire' })
    event.remove({ output: 'createaddition:electrum_wire' })
    event.remove({ output: 'createaddition:spool' })
    event.remove({ output: 'createaddition:copper_spool' })
    event.remove({ output: 'createaddition:gold_spool' })
    event.remove({ output: 'createaddition:electrum_spool' })
    event.remove({ output: 'createaddition:festive_spool' })
    event.remove({ output: 'createaddition:copper_rod' })
    event.remove({ output: 'createaddition:iron_rod' })
    event.remove({ output: 'createaddition:gold_rod' })
    event.remove({ output: 'createaddition:electrum_rod' })
    event.remove({ output: 'createaddition:brass_rod' })
    event.remove({ output: 'createaddition:straw' })
    event.remove({ output: 'createaddition:electric_motor' })
    event.remove({ output: 'createaddition:alternator' })
    event.remove({ output: 'createaddition:connector' })
    event.remove({ output: 'createaddition:small_light_connector' })
    event.remove({ output: 'createaddition:large_connector' })
    event.remove({ output: 'createaddition:redstone_relay' })
    event.remove({ output: 'createaddition:tesla_coil' })
    event.remove({ output: 'createaddition:modular_accumulator' })
    event.remove({ output: 'createaddition:portable_energy_interface' })
    event.remove({ output: 'createaddition:electrum_block' })

    event.remove({ id: 'torchmaster:frozen_pearl'})
    event.remove({ id: 'torchmaster:feral_flare_lantern'})

    event.remove({ id: 'petrolsparts:crafting/pneumatic_tube'})
    event.remove({ id: 'petrolsparts:mechanical_crafting/hydraulic_transmission'})

    event.remove({ id: 'grapplemod:ender_staff'})
    event.remove({ id: 'grapplemod:smithing/hook_ender'})

    event.remove({ id: 'createthrusters:alternator'})
    event.remove({ id: 'createthrusters:andesite_cable'})
    event.remove({ id: 'createthrusters:industrial_motor'})
    event.remove({ id: 'createthrusters:variable_transmission'})
    event.remove({ id: 'createthrusters:variable_transmission_from_vertical'})
    event.remove({ id: 'createthrusters:vertical_variable_transmission'})
    event.remove({ id: 'createthrusters:physics_staff'})

    event.remove({ id: 'createpropulsion:mixing/coral'})
    event.remove({ id: 'createpropulsion:crafting/cable_relay'})
    event.remove({ id: 'createpropulsion:crafting/cable'})
    event.remove({ id: 'createpropulsion:crafting/coral_generator'})
    event.remove({ id: 'createpropulsion:crafting/solid_fuel_thruster'})

    event.remove({ id: 'create_lnl:contraption_lift'})
    event.remove({ id: 'create_lnl:thruster'})

    event.remove({ id: 'dndesires:crafting/fluid_hatch'})
    event.remove({ id: 'dndesires:crafting/inverse_gearshift'})
    event.remove({ id: 'dndesires:crafting/handheld_saw'})
    event.remove({ id: 'dndesires:crafting/handheld_drill'})
    event.remove({ id: 'dndesires:hydraulic_compatcing/veridium_gen'})
    event.remove({ id: 'dndesires:hydraulic_compatcing/asurine_gen'})
    event.remove({ id: 'dndesires:hydraulic_compatcing/crimsite_gen'})
    event.remove({ id: 'dndesires:hydraulic_compatcing/ochrum_gen'})

    event.remove({id: 'createpropulsion:crushing/spruce_log'})

    event.remove({ id: 'aeronautics_utility_objects:damping_stress_bearing'})
})