#Truly Dark properties file
#Fri Apr 24 12:49:55 EDT 2026
biome_blacklist=alexscaves\:primordial_caves,alexscaves\:candy_cavity
cloud_darkness=0.5
dark_default=false
dark_end=false
dark_end_fog=0.0
dark_moon=false
dark_nether=false
dark_nether_fog=0.5
dark_overworld=true
dark_sky=true
dark_skyless=false
fog_darkness=0.5
ignore_moon_phase=false
moon_phase_intensity=1.0
only_affect_block_light=false
setup_version=Manual
sky_darkness=0.5
